<!DOCTYPE html>
<html>
<head>
    <meta name=viewport content="width=device-width, initial-scale=1">
  <meta name="csrf-token" content="{{ csrf_token() }}">

    <script type="text/javascript">
        // Get rid of the Facebook residue hash in the URI
        // Must be done in JS cuz hash only exists client-side
        // IE and Chrome version of the hack
        if (String(window.location.hash).substring(0,1) == "#") {
            window.location.hash = "";
            window.location.href=window.location.href.slice(0, -1);
        }
        // Firefox version of the hack
        if (String(location.hash).substring(0,1) == "#") {
            location.hash = "";
            location.href=location.href.substring(0,location.href.length-3);
        }
    </script>

<link rel="preload" href="{{ asset('pub-assets/wp-content/themes/sma-theme/fonts/icomoon.ttf@4bpb00') }}" as="font" crossorigin>
    
<style type="text/css">
    @font-face{font-family:'icomoon';src:url('{{ asset("pub-assets/wp-content/themes/sma-theme/fonts/icomoon.eot@4bpb00") }}');src:url('{{ asset("pub-assets/wp-content/themes/sma-theme/fonts/icomoon.eot@4bpb00#iefix") }}') format('embedded-opentype'),url('{{ asset("pub-assets/wp-content/themes/sma-theme/fonts/icomoon.ttf@4bpb00") }}') format('truetype'),url('{{ asset("pub-assets/wp-content/themes/sma-theme/fonts/icomoon.woff@4bpb00") }}') format('woff'),url('{{ asset("pub-assets/wp-content/themes/sma-theme/fonts/icomoon.svg@4bpb00#icomoon") }}') format('svg');font-weight:normal;font-style:normal;font-display:block}

    .wrapper {
    /* -webkit-flex-grow: 1;
    -moz-flex-grow: 1;
    -ms-flex-grow: 1;
    flex-grow: 1;
    margin: 60px 0 100px;
    font-weight: 300;
    position: relative; */
}
.my-text-active{
    color: #2BC246 !important;
}
    </style>
    
    <title>
        @hasSection ('title')
        @yield('title') - Sell My App
    @else
        Sell My App
    @endif
    </title>
    <meta name='robots' content='max-image-preview:large' />
    
    <!-- Open Graph Meta Tags & Twitter Card generated by Social Warfare v1.4.1 http://warfareplugins.com -->
    <meta property="og:type" content="article" /> 
    <meta property="og:title" content="Home" />
    <meta property="og:description" content="Choose from hundreds of top quality source codesfor iOS, iWATCH, Android, Unity" />
    {{-- <meta property="og:url" content="https://www.sellmyapp.com/" /> --}}
    <meta property="og:site_name" content="Sell My App" />
    <meta property="article:published_time" content="2014-05-19T14:28:38+02:00" />
    <meta property="article:modified_time" content="2020-04-16T19:44:16+02:00" />
    <meta property="og:updated_time" content="2020-04-16T19:44:16+02:00" />
    <meta property="fb:app_id" content="529576650555031" />
    <script type="text/javascript">function parentIsEvil() { var html = null; try { var doc = top.location.pathname; } catch(err){ }; return(doc != "/wp-admin/customize.php"); }; if (top.location != self.location && parentIsEvil()) { top.location = self.location.href; };</script>
    <style>@font-face {font-family: "sw-icon-font";src:url("{{ asset('pub-assets/wp-content/plugins/social-warfare/fonts/sw-icon-font.eot') }}");src:url("{{ asset('pub-assets/wp-content/plugins/social-warfare/fonts/sw-icon-font.eot@#iefix') }}") format("embedded-opentype"),url("{{ asset('pub-assets/wp-content/plugins/social-warfare/fonts/sw-icon-font.woff') }}") format("woff"), url("{{ asset('pub-assets/wp-content/plugins/social-warfare/fonts/sw-icon-font.ttf') }}") format("truetype"),url("{{ asset('pub-assets/wp-content/plugins/social-warfare/fonts/sw-icon-font.svg#1445203416') }}") format("svg");font-weight: normal;font-style: normal;}</style>
    <!-- Open Graph Meta Tags & Twitter Card generated by Social Warfare v1.4.1 http://warfareplugins.com -->

    <link rel='dns-prefetch' href='//s.w.org' />
    <link rel='stylesheet' id='wp-block-library-css'  href='{{ asset("pub-assets/wp-includes/css/dist/block-library/style.min.css@ver=7c17d94189e1a60690b56152a1fc3521.css") }}' type='text/css' media='all' />
    <link rel='stylesheet' id='social_warfare-css'  href='{{ asset("pub-assets/wp-content/plugins/social-warfare/css/style.css@ver=7c17d94189e1a60690b56152a1fc3521.css") }}' type='text/css' media='all' />
    <link rel='stylesheet' id='sma-theme-style-css'  href='{{ asset("pub-assets/wp-content/themes/sma-theme/style.css@ver=7c17d94189e1a60690b56152a1fc3521.css") }}' type='text/css' media='all' />
    <script type='text/javascript' defer src='{{ asset("pub-assets/wp-content/themes/sma-theme/js/combine-libs.js@ver=7c17d94189e1a60690b56152a1fc3521") }}' id='jquery-js'></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ion-rangeslider/2.3.1/css/ion.rangeSlider.min.css"/>
    
    <script type='text/javascript' src='{{ asset("pub-assets/wp-content/plugins/easy-digital-downloads/assets/js/edd-ajax.js@ver=7c17d94189e1a60690b56152a1fc3521") }}' id='edd-ajax-js'></script>
<script type='text/javascript' src='{{ asset("pub-assets/wp-content/plugins/social-warfare/script.min.js?ver=7c17d94189e1a60690b56152a1fc3521") }}' id='social_warfare_script-js'></script>
<link rel="https://api.w.org/" href="{{ asset('pub-assets/wp-json/') }}" /><link rel="alternate" type="application/json" href="{{ asset('pub-assets/wp-json/wp/v2/pages/31') }}" /><link rel="EditURI" type="application/rsd+xml" title="RSD" href="https://www.sellmyapp.com/xmlrpc.php?rsd" />
<link rel="wlwmanifest" type="application/wlwmanifest+xml" href="{{ asset('pub-assets/wp-includes/wlwmanifest.xml') }}" /> 

<link rel="canonical" href="https://www.sellmyapp.com/" />
<link rel='shortlink' href='https://www.sellmyapp.com/' />
<link rel="alternate" type="application/json+oembed" href="{{ asset('pub-assets/wp-json/oembed/1.0/embed@url=https%3A%2F%2Fwww.sellmyapp.com%2F') }}" />
<link rel="alternate" type="text/xml+oembed" href="{{ asset('pub-assets/wp-json/oembed/1.0/embed@url=https%3A%2F%2Fwww.sellmyapp.com%2F&#038;format=xml') }}" />
<meta name="generator" content="Easy Digital Downloads v2.1.9" />
<meta name="generator" content="EDD FES v2.2.10" />

		<!-- GA Google Analytics @ https://m0n.co/ga -->
		<script async src="https://www.googletagmanager.com/gtag/js?id=G-ZMVWQZCJKB"></script>
		<script>
			window.dataLayer = window.dataLayer || [];
			function gtag(){dataLayer.push(arguments);}
			gtag('js', new Date());
			gtag('config', 'G-ZMVWQZCJKB');
		</script>

	    <link rel="search" type="application/opensearchdescription+xml" title="Sell My App" href="/opensearch.xml"/>
    		<script type="text/javascript">
			/* <![CDATA[ */
			(function() {
				if (!window.mc4wp) {
					window.mc4wp = {
						listeners: [],
						forms    : {
							on: function (event, callback) {
								window.mc4wp.listeners.push({
									event   : event,
									callback: callback
								});
							}
						}
					}
				}
			})();
			/* ]]> */
		</script>

<link rel='shortcut icon' type='image/x-icon' href='{{ asset("admin-assets/assets/img/favicon-sellmyapp.ico") }}' />
		    
</head>
<body class="home page-template-default page page-id-31">
<header class="site-header remodal-fixed-item">
    <nav class="navbar navbar-default">
        <div class="container">
            <div class="navbar-header">
                <a class="navbar-brand" href="{{ route('front.home') }}">
                    <img class="logo" width="220"
                         src="{{ asset('pub-assets/wp-content/themes/sma-theme/images/sma-logo.svg') }}"
                         alt="sellmyapp.com"/>
                </a>
            </div>
            <div id="header-links">
                <ul class="nav navbar-nav" id="header-left-links">
                    <li>
                                                <div class="default-search">
                            <form role="search" method="get" id="searchform" class="search-form"
                                  action="https://www.sellmyapp.com/">
                                <input class="search-input" type="text" value="" name="s"
                                       id="search-field" placeholder="Search"/>
                                <a class="search-submit" href="#" id="search-submit"><span class="ic ic-search"></span></a>
                            </form>
                        </div>
                    </li>
                </ul>

                <ul class="nav navbar-nav navbar-right">
                    <li>
                                                <a class="cart-link" href="#" id="cart_link">
                            <span class="number-notification hidden">
                                0                            </span>
                            <span class="ic ic-cart"></span>
                        </a>

                        <div class="cart-contents">
                            <div class="cart-tip"></div>
<div class="cart-heading"><span class="ic ic-cart"></span>Shopping Cart is empty.</div>
                        </div>
                        <input id="cart_nonce" type="hidden" value="1be600e877"/>
                    </li>
                                            <li>
                            <a class="login-link" id="login_link" href="#">Log in</a>
                        </li>
                        <li>
                            <a class="btn btn-default signup-link" id="signup_link" href="#">Sign up</a>
                        </li>
                                    </ul>
            </div>
        </div>
    </nav>
    <nav class="header-second-nav">
        <div class="container">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#header-nav"
                    aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <div class="collapse navbar-collapse" id="header-nav">
                <ul class="nav navbar-nav">
                    <li>
                        <a href="{{ route('temp.game') }}">Game templates</a>
                    </li>
                    <li>
                        <a href="{{ route('temp.app') }}">App templates</a>
                    </li>
                    <li>
                        <a href="{{ route('temp.limited-offers') }}">Limited offers</a>
                    </li>
                    <li>
                        <a href="{{ route('temp.how-to-make-app') }}">How to make an app</a>
                    </li>
                                                <li>
                                <a href="{{ route('temp.reskinned-express') }}">Reskinned express</a>
                            </li>
                                                                <li class="pull-right">
                        <a href="{{ route('temp.sell-your-app') }}">Sell your app</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
    <div class="hidden" id="login_popup_content">
        <div id="login_popup_ajax_content"></div>
            </div>
    <div class="hidden" id="signup_popup_content">
        <div id="signup_popup_ajax_content"></div>
            </div>
<nav class="header-second-nav header-sticky">
    <div class="container">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#header-nav-sticky" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
        <div class="collapse navbar-collapse" id="header-nav-sticky">
            <ul class="nav navbar-nav">
                <li>
                    <a href="{{ route('temp.game') }}">Game templates</a>
                </li>
                <li>
                    <a href="https://www.sellmyapp.com/downloads/subcategory/utilities/">App templates</a>
                </li>
                <li>
                    <a href="https://www.sellmyapp.com/limited-offer/">Limited offers</a>
                </li>
                <li>
                    <a href="https://www.sellmyapp.com/how-to-make-an-app-with-sellmyapp/">How to make an app</a>
                </li>
                                        <li>
                            <a href="https://www.sellmyapp.com/reskinned-express/">Reskinned express</a>
                        </li>
                                                                    <li class="pull-right" style="margin-left: 10px;">
                                        <a class="cart-link" href="#" id="cart_link">
                            <span class="number-notification hidden">
                                0                            </span>
                        <span class="ic ic-cart"></span>
                    </a>
                    <input id="cart_nonce" type="hidden" value="1be600e877"/>
                </li>
                <li class="pull-right">
                    <a href="https://www.sellmyapp.com/selling-your-apps/">Sell your app</a>
                </li>
            </ul>
        </div>
    </div>
</nav>

@yield('content')

<!-- wrapper -->
<footer class="site-footer">
    <div class="container">
        <div class="row">
            <div class="col-sm-4 col-sm-offset-2 footer-nav-links">
                <h2>Platforms</h2>
                <ul id="menu-footer-top" class="footer-category-menu clearfix"><li id="menu-item-4130" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-4130"><a href="https://www.sellmyapp.com/downloads/category/ios/">iOS</a></li>
<li id="menu-item-4129" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-4129"><a href="https://www.sellmyapp.com/downloads/category/android/">Android</a></li>
<li id="menu-item-5493" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-5493"><a href="https://www.sellmyapp.com/downloads/category/unity/">Buy Unity Source Codes</a></li>
</ul>            </div>
            <div class="col-sm-4 footer-nav-links">
                <h2>Navigation</h2>
                <ul id="menu-footer-1" class="menu"><li id="menu-item-4221" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-4221"><a href="https://www.sellmyapp.com/selling-your-apps/">Sell your app</a></li>
<li id="menu-item-4387" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-4387"><a href="https://www.sellmyapp.com/blog/">Blog</a></li>
<li id="menu-item-35196" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-35196"><a href="https://www.sellmyapp.com/how-to-make-an-app-with-sellmyapp/">How to make an app</a></li>
</ul>            </div>
            <div class="col-sm-4 footer-nav-links">
                <h2>How it works</h2>
                <ul id="menu-footer-2" class="menu"><li id="menu-item-4431" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-4431"><a href="https://www.sellmyapp.com/buy-app-source-code/">Buy iOS apps</a></li>
<li id="menu-item-4432" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-4432"><a href="https://www.sellmyapp.com/buy-app-source-code/">Buy Android apps</a></li>
<li id="menu-item-2672" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-2672"><a href="https://www.sellmyapp.com/help-support/">Help / Support</a></li>
</ul>            </div>
            <div class="col-sm-4 footer-nav-links">
                <h2>About</h2>
                <ul id="menu-footer-3" class="menu"><li id="menu-item-4061" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-4061"><a href="https://www.sellmyapp.com/developer-terms-conditions/">Terms &amp; Conditions</a></li>
<li id="menu-item-4062" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-4062"><a href="https://www.sellmyapp.com/privacy-policy/">Privacy Policy</a></li>
</ul>            </div>
        </div>
    </div>
</footer>
        <script type="text/javascript">
            jQuery(document).on("DOMNodeInserted", function () {
                // Lock uploads to "Uploaded to this post"
                jQuery('select.attachment-filters [value="uploaded"]').attr('selected', true).parent().trigger('change');
            });
        </script>
                <!-- Google Analytics -->
        <script>
            window.ga=window.ga||function(){(ga.q=ga.q||[]).push(arguments)};ga.l=+new Date;
            ga('create', 'UA-53481319-1', 'www.sellmyapp.com');
            ga('send', 'pageview');
        </script>
        
        <script defer src="{{ asset('pub-assets/wp-includes/js/main-page.min.js') }}"></script>

        <!-- End Google Analytics -->


        <script type='text/javascript' id='all-pages-scripts-js-extra'>
/* <![CDATA[ */
var global_vars = {"ajax_url":"https:\/\/www.sellmyapp.com\/wp-admin\/admin-ajax.php","checkout_url":"https:\/\/www.sellmyapp.com\/checkout"};
/* ]]> */
</script>
<script type='text/javascript' defer src='{{ asset("pub-assets/wp-content/themes/sma-theme/js/all-pages.js@ver=7c17d94189e1a60690b56152a1fc3521d") }}' id='all-pages-scripts-js'></script>
<script type='text/javascript' src='{{ asset("pub-assets/wp-includes/js/wp-embed.min.js@ver=7c17d94189e1a60690b56152a1fc3521") }}' id='wp-embed-js'></script>
<script type='text/javascript' src='{{ asset("pub-assets/wp-content/plugins/cartpauj-pm/js/jquery.iframe-transport.js@ver=7c17d94189e1a60690b56152a1fc3521") }}' id='iframe-transport-js'></script>
<script type='text/javascript' src='{{ asset("pub-assets/wp-content/plugins/cartpauj-pm/js/jquery.fileupload.js@ver=7c17d94189e1a60690b56152a1fc3521") }}' id='fileupload-js'></script>
<script type='text/javascript' id='message_system-js-extra'>

/* <![CDATA[ */
var ajax_url = "https:\/\/www.sellmyapp.com\/wp-admin\/admin-ajax.php";
/* ]]> */
</script>
<script type='text/javascript' src='{{ asset("pub-assets/wp-content/plugins/cartpauj-pm/js/script.js@ver=v1.01") }}' id='message_system-js'></script>
<script type='text/javascript' src='{{ asset("pub-assets/wp-content/themes/sma-theme/js/keywords.js@ver=7c17d94189e1a60690b56152a1fc3521") }}' id='keywords-js'></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/sweetalert2/11.7.28/sweetalert2.all.js" integrity="sha512-cD1xrn0N1tV0ze8axCp+noWgxMFlWVg22HBXUfowicWhJsnAcSXNKnwI77Bkn3yLyqGvwZ/a8M2PtOjVp5vMaw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/sweetalert2/11.7.28/sweetalert2.all.js"></script>


<script type='text/javascript' src='{{ asset("pub-assets/wp-content/plugins/cartpauj-pm/js/script.js@ver=v1.01") }}' id='message_system-js'></script>
<script src="https://code.jquery.com/jquery-3.7.0.min.js"></script>


    
    <!--jQuery-->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    
    <!--Plugin JavaScript file-->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/ion-rangeslider/2.3.1/js/ion.rangeSlider.min.js"></script>
     

    <script type="text/javascript">

        $.ajaxSetup({
          headers: {
            'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
          }
        });
        
    </script>

@yield('customJs')

</body>
</html>