@extends('front.layout.main')

<!DOCTYPE html>
<html>
<head>
    <meta name=viewport content="width=device-width, initial-scale=1">
    <script type="text/javascript">
        // Get rid of the Facebook residue hash in the URI
        // Must be done in JS cuz hash only exists client-side
        // IE and Chrome version of the hack
        if (String(window.location.hash).substring(0,1) == "#") {
            window.location.hash = "";
            window.location.href=window.location.href.slice(0, -1);
        }
        // Firefox version of the hack
        if (String(location.hash).substring(0,1) == "#") {
            location.hash = "";
            location.href=location.href.substring(0,location.href.length-3);
        }
    </script>

    <link rel="preload" href="{{ asset('pub-assets/wp-content/themes/sma-theme/fonts/icomoon.ttf@4bpb00') }}" as="font" crossorigin>
    
    <style type="text/css">
        @font-face{font-family:'icomoon';src:url('{{ asset("pub-assets/wp-content/themes/sma-theme/fonts/icomoon.eot@4bpb00") }}');src:url('{{ asset("pub-assets/wp-content/themes/sma-theme/fonts/icomoon.eot@4bpb00#iefix") }}') format('embedded-opentype'),url('{{ asset("pub-assets/wp-content/themes/sma-theme/fonts/icomoon.ttf@4bpb00") }}') format('truetype'),url('{{ asset("pub-assets/wp-content/themes/sma-theme/fonts/icomoon.woff@4bpb00") }}') format('woff'),url('{{ asset("pub-assets/wp-content/themes/sma-theme/fonts/icomoon.svg@4bpb00#icomoon") }}') format('svg');font-weight:normal;font-style:normal;font-display:block}

        .wrapper {
    /* -webkit-flex-grow: 1;
    -moz-flex-grow: 1;
    -ms-flex-grow: 1;
    flex-grow: 1;
    margin: 60px 0 100px;
    font-weight: 300;
    position: relative; */
}
    </style>
    
        <title>Sell My App &#8211; Source Code Marketplace &#8211; Buy, Sell &amp; Elevate Your App Projects with SellMyApp</title>
<meta name='robots' content='max-image-preview:large' />

<!-- Open Graph Meta Tags & Twitter Card generated by Social Warfare v1.4.1 http://warfareplugins.com -->
<meta property="og:type" content="article" /> 
<meta property="og:title" content="Home" />
<meta property="og:description" content="Choose from hundreds of top quality source codesfor iOS, iWATCH, Android, Unity" />
{{-- <meta property="og:url" content="https://www.sellmyapp.com/" /> --}}
<meta property="og:site_name" content="Sell My App" />
<meta property="article:published_time" content="2014-05-19T14:28:38+02:00" />
<meta property="article:modified_time" content="2020-04-16T19:44:16+02:00" />
<meta property="og:updated_time" content="2020-04-16T19:44:16+02:00" />
<meta property="fb:app_id" content="529576650555031" />
<script type="text/javascript">function parentIsEvil() { var html = null; try { var doc = top.location.pathname; } catch(err){ }; return(doc != "/wp-admin/customize.php"); }; if (top.location != self.location && parentIsEvil()) { top.location = self.location.href; };</script>
<style>@font-face {font-family: "sw-icon-font";src:url("{{ asset('pub-assets/wp-content/plugins/social-warfare/fonts/sw-icon-font.eot') }}");src:url("{{ asset('pub-assets/wp-content/plugins/social-warfare/fonts/sw-icon-font.eot@#iefix') }}") format("embedded-opentype"),url("{{ asset('pub-assets/wp-content/plugins/social-warfare/fonts/sw-icon-font.woff') }}") format("woff"), url("{{ asset('pub-assets/wp-content/plugins/social-warfare/fonts/sw-icon-font.ttf') }}") format("truetype"),url("{{ asset('pub-assets/wp-content/plugins/social-warfare/fonts/sw-icon-font.svg#1445203416') }}") format("svg");font-weight: normal;font-style: normal;}</style>
<!-- Open Graph Meta Tags & Twitter Card generated by Social Warfare v1.4.1 http://warfareplugins.com -->

<link rel='dns-prefetch' href='//s.w.org' />
<link rel='stylesheet' id='wp-block-library-css'  href='{{ asset("pub-assets/wp-includes/css/dist/block-library/style.min.css@ver=7c17d94189e1a60690b56152a1fc3521.css") }}' type='text/css' media='all' />
<link rel='stylesheet' id='social_warfare-css'  href='{{ asset("pub-assets/wp-content/plugins/social-warfare/css/style.css@ver=7c17d94189e1a60690b56152a1fc3521.css") }}' type='text/css' media='all' />
<link rel='stylesheet' id='sma-theme-style-css'  href='{{ asset("pub-assets/wp-content/themes/sma-theme/style.css@ver=7c17d94189e1a60690b56152a1fc3521.css") }}' type='text/css' media='all' />
<script type='text/javascript' defer src='{{ asset("pub-assets/wp-content/themes/sma-theme/js/combine-libs.js@ver=7c17d94189e1a60690b56152a1fc3521.css") }}' id='jquery-js'></script>

<script type='text/javascript' src='{{ asset("pub-assets/wp-content/plugins/easy-digital-downloads/assets/js/edd-ajax.js@ver=7c17d94189e1a60690b56152a1fc3521") }}' id='edd-ajax-js'></script>
<script type='text/javascript' src='{{ asset("pub-assets/wp-content/plugins/social-warfare/script.min.js@ver=7c17d94189e1a60690b56152a1fc3521") }}' id='social_warfare_script-js'></script>
<link rel="https://api.w.org/" href="{{ asset('pub-assets/wp-json/') }}" /><link rel="alternate" type="application/json" href="{{ asset('pub-assets/wp-json/wp/v2/pages/31') }}" /><link rel="EditURI" type="application/rsd+xml" title="RSD" href="{{ asset('pub-assets/xmlrpc.php@rsd') }}" />
<link rel="wlwmanifest" type="application/wlwmanifest+xml" href="{{ asset('pub-assets/wp-includes/wlwmanifest.xml') }}" /> 

<link rel="canonical" href="https://www.sellmyapp.com/" />
<link rel='shortlink' href='https://www.sellmyapp.com/' />
<link rel="alternate" type="application/json+oembed" href="{{ asset('pub-assets/wp-json/oembed/1.0/embed@url=https%3A%2F%2Fwww.sellmyapp.com%2F') }}" />
<link rel="alternate" type="text/xml+oembed" href="{{ asset('pub-assets/wp-json/oembed/1.0/embed@url=https%3A%2F%2Fwww.sellmyapp.com%2F&#038;format=xml') }}" />
<meta name="generator" content="Easy Digital Downloads v2.1.9" />
<meta name="generator" content="EDD FES v2.2.10" />

@section('content')

<div class="wrapper">    <div class="container">
  <div class="breadcrumbs">
      <a href="https://www.sellmyapp.com">Buy apps</a> <i class="ic ic-caret-right"></i> App license types        </div>
  <div class="row">
      <div class="col-sm-15 main-post-column">
          <h1 class="underlined-title">App license types</h1>
          <div class="blog-post-content">
              <p><strong>Single App License Agreement</strong></p>
<p>This Agreement is between the Vendor of the product and the Buyer. SellMyApp LLC, as a marketplace, bears no liability or responsibility for the products sold on its platform.</p>
<p>Under this Agreement, the Vendor grants the Buyer the right to use the purchased product for personal or commercial purposes. This right is non-exclusive, non-transferrable, and comes with no additional charges beyond the initial purchase price, except as otherwise specified.</p>
<p>This license permits usage of the product for one project, which may be your own or on behalf of a client (for personal, commercial, or non-profit purposes).</p>
<p>The resale of the purchased product, either as a standalone item or as part of a larger project, is strictly prohibited by you or your client.</p>
<p>The purchased items under this license are not to be resold or redistributed in their original format or as part of a bundle of files.</p>
<p>This license authorizes you to:</p>
<p>&#8211; Incorporate the product into a single app.<br />
&#8211; Distribute the product exclusively as binary (distribution of the source code is expressly forbidden).<br />
&#8211; Use the product for commercial purposes.<br />
&#8211; Modify or further develop the product&#8217;s code.</p>
<p>The Vendor retains all intellectual property rights in the product. SellMyApp LLC disclaims all warranties, express or implied, including any warranties of accuracy, non-infringement, merchantability and fitness for a particular purpose. SellMyApp LLC disclaims any and all liability for the acts, omissions and conduct of any third parties in connection with or related to your use of the platform and/or any SellMyApp LLC services.</p>
<p>The Buyer agrees to indemnify and hold harmless SellMyApp LLC from any claims resulting from any action taken by the Buyer that infringes the rights of any person or entity.</p>
<p><strong>Multi-App License Agreement</strong></p>
<p>This Agreement follows the same terms as the Single App License Agreement, but permits usage of the product for multiple projects, which may be your own or on behalf of multiple clients (for personal, commercial, or non-profit purposes). The product may be incorporated into multiple apps, used for commercial purposes in multiple apps, and modified or further developed in multiple apps.</p>
          </div>
      </div>
      <div class="col-sm-5">
          <ul class="sidebar">
              <li class="widget"><h2 class="widget-title">Help / Support</h2><div class="menu-help-support-container"><ul id="menu-help-support" class="menu"><li id="menu-item-4187" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-4187"><a href="https://www.sellmyapp.com/help-support/">Help / Support</a></li>
</ul></div></li><li class="widget"><h2 class="widget-title">Contact Us</h2>			<div class="textwidget"><img alt="" src="https://www.sellmyapp.com/wp-content/uploads/contactus.png" style="padding: 13px;"/></div>
</li><li class="widget"><h2 class="widget-title">Buying App Components</h2><div class="menu-buying-source-codes-container"><ul id="menu-buying-source-codes" class="menu"><li id="menu-item-4183" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-4183"><a href="https://www.sellmyapp.com/buy-app-source-code/">Buy App Source Code</a></li>
<li id="menu-item-4313" class="menu-item menu-item-type-post_type menu-item-object-page current-menu-item page_item page-item-2665 current_page_item menu-item-4313"><a href="https://www.sellmyapp.com/app-license-types/" aria-current="page">App license types</a></li>
</ul></div></li><li class="widget"><h2 class="widget-title">Selling App Components</h2><div class="menu-selling-app-components-container"><ul id="menu-selling-app-components" class="menu"><li id="menu-item-4184" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-4184"><a href="https://www.sellmyapp.com/sell-app-source-code/">Sell Your App Source Code</a></li>
<li id="menu-item-4322" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-4322"><a href="https://www.sellmyapp.com/preparing-your-code/">Preparing your code</a></li>
<li id="menu-item-4336" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-4336"><a href="https://www.sellmyapp.com/uploading-your-code/">Uploading your Code</a></li>
</ul></div></li>                </ul>
      </div>
  </div>

</div>
</div><!-- wrapper -->

@endsection